name: OGStarTracker CI
on:
  push:
    branches: ["main", "beta"]
  pull_request:
    branches: ["**"]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        path:
          - check: 'esp32_wireless_control/firmware'
            exclude: '(shared)'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
